### PR TITLE
kotlin: Add a Java demo project

### PR DESCRIPTION
**Pull request by ebraminio**

### CODE REVIEW

**Comment by cosinekitty** [comment]
I like it! Like I mentioned in #173, it would be helpful if I had a script that can run all (future) Java demos to produce deterministic output to the console, that can be redirected to a file and compared with known-correct text files. If you can create a bash script to run from Linux and Mac OS, I can add a call to that script in the right place from my main unit test script. (Currently I do not validate the demos from Windows, but that could change in the future.)

**Comment by ebraminio** [comment]
Its tests will run with `./gradlew test` and its main will run with `./gradlew run`:

```
$ ./gradlew test       

BUILD SUCCESSFUL in 1s
3 actionable tasks: 1 executed, 2 up-to-date
$ ./gradlew run        

> Task :run
2022-03-22T00:04:34.034Z

BUILD SUCCESSFUL in 941ms
2 actionable tasks: 1 executed, 1 up-to-date
```

**Comment by cosinekitty** [comment]
OK, that should be enough for me to work with. Thank you for all your work in helping me get this started!

**Comment by ebraminio** [comment]
> OK, that should be enough for me to work with. Thank you for all your work in helping me get this started!

Great. Thank you 🙏

**Comment by cosinekitty** [comment]
One question: is it possible for me to run the program without getting the gradlew output too? Right now I see this:

```
$ ./gradlew run --console=plain
> Task :compileJava UP-TO-DATE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE

> Task :run
2022-03-22T00:12:04.004Z

BUILD SUCCESSFUL in 950ms
2 actionable tasks: 1 executed, 1 up-to-date
```

I would like to do something like this and capture only the program's output:

```
$ run_this_thing > t.txt
$ more t.txt
2022-03-22T00:12:04.004Z
```

**Comment by ebraminio** [comment]
> One question: is it possible for me to run the program without getting the gradlew output too? 

Oh, sure, first needs this from https://stackoverflow.com/a/71094727 :

```diff
diff --git a/demo/java/build.gradle.kts b/demo/java/build.gradle.kts
index 84b58f3..5254a13 100644
--- a/demo/java/build.gradle.kts
+++ b/demo/java/build.gradle.kts
@@ -21,6 +21,13 @@ application {
     mainClass.set("io.github.cosinekitty.astronomy.demo.Main")
 }
 
+tasks.jar {
+    manifest.attributes["Main-Class"] = "io.github.cosinekitty.astronomy.demo.Main"
+    val dependencies = configurations.runtimeClasspath.get().map(::zipTree)
+    from(dependencies)
+    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
+}
+
 tasks.getByName<Test>("test") {
     useJUnitPlatform()
 }
```

Then `./gradlew jar` and finally

```
java -jar build/libs/astronomy-demo-0.0.1.jar
2022-03-22T12:23:39.039Z
```

**Pull request merged**
