### PR TITLE
add astro_time_t and test TerrestrialTime

### PR DESCRIPTION
**Pull request by DannyRavi**
Finally, after some delay, I converted a part of the program from C code to Go, and especially I tested the "TerrestrialTime" part in both languages and the result was the same. I also converted "astro_time_t" to Go equivalent. I am waiting for the implementation of the next step if the completed parts are approved. Thanks.

### CODE REVIEW

**Comment by cosinekitty** [comment]
Hi @DannyRavi! This is a good start, and I'm glad to see you are still working on it. I will need to do a few things over the weekend to help make more progress. I will update the code generator to process this Go code, so that it can be put in the correct place (`generate/template/`) and the generated code will go into `/source/golang/`. We will also need to separate the test code so that the astronomy.go does not have a `main` function. I need to learn more about Go, but I'm pretty sure there is a standard way of adding unit tests so that they don't interfere with other code using the library. Thank you for your work on this! I will let you know in a day or two when I have done the steps I mentioned above.

**Comment by cosinekitty** [comment]
Hi again Danny! As you can see, I merged your changes into the `golang` branch. I also made some more changes:

* The source code that we edit goes in `generate/template/astronomy.go`. That is where we need to make all changes.
* I updated the code generator to read from `generate/template/astronomy.go` and write to `source/golang/astronomy.go`. We should never directly edit the file `source/golang/astronomy.go` because it is automatically generated every time we run the full test suite. Soon there will be tables of numbers that the code generator needs to inject into the Go code. I will help you with that part over time, as we continue.
* I added a [go.mod](https://github.com/cosinekitty/astronomy/blob/golang/source/golang/go.mod) file that defines the astronomy package, and changed the name of the package to "astronomy" inside `astronomy.go`.
* I removed the `main` function from astronomy.go because it is going to be a library, not a program.
* I added a tiny unit test file [astronomy_test.go](https://github.com/cosinekitty/astronomy/blob/golang/source/golang/astronomy_test.go). It shows an example of testing that the function `TerrestrialTime` is working correctly. This is where we need to add all the unit tests. You can run the unit tests from this directory by running `go test`.

When you make future changes, again you should be editing the source code in the `generate/template` directory. Then you will need to run the full test suite to generate the target code and run all the tests. You will need to change into the `generate` directory and execute `./run` (Linux or Mac) or `run.bat` (Windows). It will automate the process of running the code generator and unit tests for all languages (C, C#, JavaScript, Python, Kotlin, and Go).

Unfortunately, this script takes a while to finish, and you will need to install dependencies for all the supported programming languages [as mentioned here](https://github.com/cosinekitty/astronomy/blob/master/generate/README.md).

I hope this helps!

**Comment by cosinekitty** [comment]
I finally fixed some problems with the way Git and Windows interacted to cause line-ending problems with Go source code. Also, I still want to make a change in how functions report and detect errors.

The C code that you based your changes on is probably not the most natural way to handle this in Go. In the C code, I made an unusual decision to include a `status` field in structs, and to return the structs by value. This is because a C function can only return a single type, and I wanted to avoid having to pass a pointer to an error code, or have to call some separate function to detect errors everywhere.

However, in Go, functions can return tuple types. This allows a more [idiomatic way of reporting and handling errors in Go](https://go.dev/blog/error-handling-and-go). I think we should follow that pattern so that experienced Go programmers easily recognize and understand how to use Astronomy Engine.

So I will go back and refactor the types to separate error reporting from return data. I will do that later today.

**Comment by cosinekitty** [comment]
Oh, one more thing: because C does not have namespaces or modules, I have to prefix a lot of things with "Astronomy_" or "astro_" to avoid name collisions. We don't need to do that in Go because everything is contained inside the module "astronomy". So I will make a quick pass of renaming things today also. After that, we can continue that pattern of naming.

**Comment by cosinekitty** [comment]
I think we are both learning Go at the same time. One thing I discovered is that names beginning with upper case are for public/exported symbols. Names beginning with lower case are for private/internal symbols. There is a lot of good information in the [Go Style Guide](https://google.github.io/styleguide/go/index). I think we should both read this document and try to follow it as much as possible.

I also think the [C# version of Astronomy Engine](https://github.com/cosinekitty/astronomy/blob/master/source/csharp/astronomy.cs) will be a better reference for how to name things in Go than the C version. Both are more modern languages with concepts like interfaces, namespaces, etc. There is also  more of a similar culture of using PascalCase and camelCase naming in both languages.

In commit 9756c1ebe07f59cc509dde665ee0314015b12161 I renamed things to follow Go's preferred style, and the requirement of public/private specification by having an upper/lower case first character in the name.

**Comment by DannyRavi** [comment]
Hi @cosinekitty In the past, I tried to translate most of the program from C code to Golang, but the code was very complicated and I could not translate the program by dividing and conquering method. Finally, I was able to translate a part of the program with the help of one of the examples, but I did not understand the schematic of the program.
I am also familiar with the many concepts of Golang language, I am also familiar with the topics of pubilc and private names, but because I did not fully understand the structure of the program, I left these items to refactoring in the near future.

**Comment by cosinekitty** [comment]
OK, that makes sense. Yes, it is very difficult to come into a project this big and know where to start. I appreciate your willingness and effort! I'm thinking more about using the C# code as the reference than the C code. Let me think more about what the next steps should be. I may have to make some kind of diagram or document of dependencies, to figure out what is the best sequence. This will take a little bit of time, but I will reply back here.

**Comment by DannyRavi** [comment]
I am waiting for the next step to be determined. Now, out of curiosity, I ran the C program on the Arduino, and there were limited resources on the Arduino Uno, but esp8266(node mcu) runs well with a few changes, for example, on ASTRONOMY_ENGINE_WHOLE_SECOND, and although incorrect information is output from the serial port. It seems that microsecond time unit can be activated with some changes and using SysTick or micros() or hardware timer.

**Pull request merged**
