### PR TITLE
Add support for Julian calendar dates

### PR DESCRIPTION
**Pull request by sbooth**
Initial implementation. Test cases to follow.

### CODE REVIEW

**Comment by sbooth** [comment]
Test cases from [JD Date/Time Converter](https://ssd.jpl.nasa.gov/tools/jdc/):

| Julian Calendar Date | JD |
| --- | --- |
| 1582-10-04 | 2299159.5 |
| 1000-01-01 | 2086307.5 |
| -4712-01-01 12:00 | 0 |
| -4712-01-01 | -0.5 |
| -5000-01-01 18:00 | -105191.75 |

**Comment by sbooth** [comment]
I added a function `Astronomy_MakeTime_Gregorian` which should be equivalent to the existing `Astronomy_MakeTime` but I'm curious to compare the output of the two and make sure they are the same.

I also added a function, with a name I'm not particularly fond of, called `Astronomy_MakeTime_Auto` which will select the Julian or Gregorian calendar to interpret the date based on the date of the Julian-Gregorian calendar changeover.

**Comment by cosinekitty** [comment]
I like the direction you are heading. I'm not sure we need MakeTime_Gregorian. I would prefer using MakeTime as the gregorian implementation. It has been tested to work correctly for all years from -999,999 to +999,999.  Also, I'm encountering some build errors:

```
../../source/c/astronomy.c: In function ‘Astronomy_MakeTime_Gregorian’:
../../source/c/astronomy.c:1185:43: error: expected ‘;’ before ‘if’
 1185 |     J -= (3 * ((g + 184) / 100)) / 4 - -38
      |                                           ^
      |                                           ;
 1186 | 
 1187 |     if (cycles > 0)
      |     ~~                                     
../../source/c/astronomy.c: In function ‘Astronomy_MakeTime_Auto’:
../../source/c/astronomy.c:1225:25: error: ‘y’ undeclared (first use in this function); did you mean ‘yn’?
 1225 |     if (year < 1582 || (y == 1582 && (m < 10 || (m == 10 && d < 15))))
      |                         ^
      |                         yn
../../source/c/astronomy.c:1225:25: note: each undeclared identifier is reported only once for each function it appears in
../../source/c/astronomy.c:1225:39: error: ‘m’ undeclared (first use in this function)
 1225 |     if (year < 1582 || (y == 1582 && (m < 10 || (m == 10 && d < 15))))
      |                                       ^
../../source/c/astronomy.c:1225:61: error: ‘d’ undeclared (first use in this function)
 1225 |     if (year < 1582 || (y == 1582 && (m < 10 || (m == 10 && d < 15))))
      |                                                             ^
../../source/c/astronomy.c:1229:1: error: control reaches end of non-void function [-Werror=return-type]
 1229 | }
      | ^
cc1: all warnings being treated as errors

```

**Comment by sbooth** [comment]
I deleted the `Astronomy_MakeTime_Gregorian` function and use `Astronomy_MakeTime` instead. I also attempted to update the documentation for `Astronomy_MakeTime` to clarify that the dates it accepts are Gregorian dates.

**Pull request merged**
