### PR TITLE
jvm demos: Simplify main function

### PR DESCRIPTION
**Pull request by ebraminio**
Simplify main function part of Java / Kotlin demos and makes them similar to each others.

### CODE REVIEW

**Comment by cosinekitty** [comment]
Looks good! It is nice to keep the Java and Kotlin demos similar.

**Comment by cosinekitty** [comment]
@ebraminio For some reason it works on my local system, but fails on GitHub Actions:
https://github.com/cosinekitty/astronomy/runs/6265747923?check_suite_focus=true#step:12:855
Any idea why this happens?  Perhaps a different version of Java?

**Comment by cosinekitty** [comment]
It looks like we can't use `isEmpty` in Java 1.8?
https://youtrack.jetbrains.com/issue/IDEA-242790

**Comment by cosinekitty** [comment]
I used `!isPresent` instead of `isEmpty`... that fixed it.

**Comment by ebraminio** [comment]
> I used !isPresent instead of isEmpty... that fixed it.

That indicates the project structure doesn't enforce a specific Java language version (my bad) and needs something like https://docs.gradle.org/current/userguide/building_java_projects.html thus uploaded https://github.com/cosinekitty/astronomy/pull/214

**Pull request merged**
