### PR TITLE
single step to start astronomy in golnag  

### PR DESCRIPTION
**Pull request by DannyRavi**
single step to start astronomy in golnag 
astronomy.go ready to start.

### CODE REVIEW

**Comment by cosinekitty** [comment]
Hi @DannyRavi, and welcome to the project! I can see you are interested in adding support for Go to Astronomy Engine. That is very cool!

Before we proceed with this, there are some things you need to know, because this may be a lot more work than you realize. I didn't want you to start something only to find out it's more than you have time for.

* Most of the effort would involve porting unit tests and documentation. All of the Astronomy Engine functions are rigorously tested across the supported languages.
* The source code is written in the [generate/template](https://github.com/cosinekitty/astronomy/tree/master/generate/template) directory, and includes special tags where a custom code generator adds tables of calculated numbers. So that is where you would put your astronomy.go file.
* The code generator is [generate.c](https://github.com/cosinekitty/astronomy/blob/master/generate/generate.c) and it will have to be updated to understand how to generate the tables of numbers for Go. This program would take `generate/template/astronomy.go` and process it to produce compilable code.
* The documentation is all extracted from comments in the source code, and converted to GitHub flavored Markdown (GFM). This generally involves creating custom tools, because existing tools either don't produce Markdown, or they do so in an unhelpful format for this project.
* Please take a look at this [contributor documentation](https://github.com/cosinekitty/astronomy/tree/master/generate#readme). It explains what tools you need and how to run unit tests and documentation generators, in order to contribute to Astronomy Engine. I strongly recommend following those steps until you can execute the `generate/run` script all the way to successful completion. Otherwise, it is very difficult to submit a working PR.

If you are motivated to take the lead on this amount of work, I will be very happy to help and guide the process. We would create a separate branch for you to work in, because the `master` branch is for officially released code only.

Experience has shown that adding support for a new programming takes about one or two months of daily work.

What do you think about all this? Hopefully what I have said is not too scary, LOL. It really would be nice to support the Go programming language, because it is a clean and efficient language that many people enjoy using.

**Comment by DannyRavi** [comment]
It is my honor to participate in this project.
I have read your explanation points and I am trying to follow them for this project.
I also agree that a branch should be created for development in Golang language.
Of course, I may make many mistakes at the beginning. But this does not mean to be afraid to continue.
Science requires a lot of patience.

**Comment by DannyRavi** [comment]
Hi @cosinekitty. It is my honor to participate in this project.
I have read your explanation points and I am trying to follow them for this project.
I also agree that a branch should be created for development in Golang language.
Of course, I may make many mistakes at the beginning. But this does not mean to be afraid to continue.
Science requires a lot of patience.

**Comment by cosinekitty** [comment]
I just added a new [golang](https://github.com/cosinekitty/astronomy/tree/golang) branch. You will probably need to delete your existing fork and PR, and start over with a new one.

I would recommend starting one small step at a time, like this:

1. Make sure you can install all the tools you need, as explained in the contributor documentation, like I mentioned above. Before you change anything, please verify that `generate/run` goes all the way to the end without any errors, and you see a large "All Tests Passed" message when it finishes.
2. Once you get that working, try translating the `astro_time_t` type from C to Go. This type is fundamental for doing astronomy calculations.
3. Once you finish that, I will help figure out how to create unit tests and run them automatically in GitHub, just like we do for every other supported programming language.
4. I will also help figure out how to generate documentation from comments in the Go source code so we have live documentation for people to use.

I think solving all the basic problems for just the `astro_time_t` type will take some time, but once that is finished, everything else will pick up speed very rapidly.

Also, I know that Go is somewhat opinionated about how things are named, and I believe we should use [`go fmt`](https://go.dev/blog/gofmt) as part of the build process to conform to common formatting patterns. So feel free to adapt the names of things to whatever is common usage in Go, so long as the names closely match the other languages.

Please let me know what you think, and I will be happy to help whenever you run into any problems. Thank you again!

**Comment by DannyRavi** [comment]
Based on the suggestions you wrote, I will continue the task.

**Pull request closed without merging**
