### PR TITLE
Docs: glossary placeholders

### PR DESCRIPTION
**Pull request by matheo**
You can checkout the initial sections here:
https://matheo.github.io/astronomy/#/glossary/observers

I will need some time to figure out a componetized way to manipulate an animated SolarSystem, and move the camera around it to illustrate some of the concepts.

### CODE REVIEW

**Comment by cosinekitty** [comment]
I like the overall style, but I have something different in mind for the glossary structure:

* I think it will be best to have a single page per defined term, without tabbing.
* Ability to deep-link from source code comments (jsdoc, etc).
* Ability to link from related concepts. For example, the page for Universal Time could link to the page for Terrestrial Time, so that the two concepts could be contrasted.
* Is it possible to dynamically generate the website pages during deployment, based on some simple kind of wiki/markdown formatting? Or just let me know how I create new content... I will learn it!

This would be something like a miniature "Wikipedia" but just for astronomy concepts.

**Comment by matheo** [comment]
> Ability to deep-link from source code comments (jsdoc, etc).

Do you mean something different to `@see {@link http://astroengine.org/glossary/time-scales#terrestrial-time|Terrestrial Time}`?

> Ability to link from related concepts. For example, the page for Universal Time could link to the page for Terrestrial Time, so that the two concepts could be contrasted.

Yeah, I copy pasted the tabs from the Coordinate Systems, where my plan for the `tabs` is related to the manipulation of an animated "canvas" at the bottom.

> Is it possible to dynamically generate the website pages during deployment

My plan is not complete tho, I don't see how generated-code would be better than a custom web application with the docs. I have to introduce the animations that I have in mind, I will mark this PR as "WIP" until it's ready ;)

**Comment by cosinekitty** [comment]
OK, the ability to link from documentation embedded in the source code sounds good. I was asking about generating the website, not so much to micromanage how you do it, but to understand how I will be able to write content for it. Because you are still planning and thinking, I will gladly wait. I'm sure I will understand when the time is right!

**Comment by matheo** [comment]
So, to maintain the docs easily, I've played with the `jsdoc` tutorials and they are now included in the HTML output:

image

These markdowns can be referenced in the code with the [JSDoc {@tutorial time-scales}](https://jsdoc.app/about-tutorials.html).

I do load those markdowns inside each Angular Component:
https://matheo.github.io/astronomy/#/glossary/observers

and I need those custom Angular Component to include the demo animations that I want to add later on. WDYT?

P/D. I'm learning some new stuff too :D

**Comment by cosinekitty** [comment]
Yes, I like that format! And yes, it's fine to bring in dependencies as you think best for maintaining the documentation and website. I only want to keep the Astronomy Engine release code itself free of any dependencies.

**Comment by matheo** [comment]
@cosinekitty sure, it's not needed so I full agree to keep it clean ;)

**Comment by matheo** [comment]
@cosinekitty We can disable GitHub Pages now, and finish the configuration of Netlify after merge this PR :)

**Comment by cosinekitty** [comment]
Does this mean you are ready for me to merge it now?

**Comment by matheo** [comment]
Yes, after this Pull Request I will finish the Netlify configuration :)

**Comment by cosinekitty** [comment]
The deed is done!

**Pull request merged**
