### PR TITLE
Support microsecond time resolution

### PR DESCRIPTION
**Pull request by KJ7LNW**
This patch adds support for microsecond time resolution on the UNIX and WIN32 platforms.

Implementation details:

Previously, the `Astronomy_CurrentTime()` function used `time(NULL)` to get the current time, thus providing 1-second resolution.  This patch uses `gettimeofday()` for UNIX and `GetSystemTimeAsFileTime()` for WIN32 platforms.  If neither are supported, it will fall back to `time()` and issue a `#warning`.  (Note that windows.h defines ARRAYSIZE, which may or may not be compatible.  Thus, the internal define `ARRAYSIZE` is renamed to `ASTRO_ARRAYSIZE`.)

The UNIX code was tested in Linux, and in [arm-eabi-none](https://developer.arm.com/downloads/-/gnu-rm) under [Newlib](https://sourceware.org/newlib/). The WIN32 code was tested using [MinGW/64](https://www.mingw-w64.org/) under [WINE](https://www.winehq.org/).

Use case:

One-second resolution is enough in most cases.  However, there are cases where higher resolutions are desirable.  For example:

We are using the astronomy.c library to control a mechanical rotor to track celestial objects (planets, stars, and satellites).  The rotor controller uses a PID controller with 100 tick/sec upsated, and tracks the velocity of the azimuth and elevation angles from the previous tick. With 1-second resolution, the PID controller jerks and oscillates once per second as it adjusts to the new position.  With at least 10-millisecond resolution (100/sec), it can calculate the per-tick velocity change and track smoothly with far less jitter.

More information about the project:
- Source using astronomy.c:
    - https://github.com/KJ7NLL/space-ham
- Lego-controlled az/el:
    - https://youtu.be/vrlw4QPKMRY
- Lego-controlled telescope focus:
    - https://youtu.be/p-5dOQG95xg
- APID+SMC control algorithm:
	- https://doi.org/10.1016/j.precisioneng.2022.01.006

### CODE REVIEW

**Comment by KJ7LNW** [comment]
FYI, the forced-pushes fixed typos in the commit comment.

**Comment by cosinekitty** [comment]
This looks great! It is much better to squeeze as much time resolution as possible from the system clock. I will try this on my home systems and see how it works.

There are a few minor things I want to change, but I'm happy to do that on my end:

* Use spaces instead of tabs for code indentation, for consistency with existing code.
* Use [ULARGE_INTEGER](https://learn.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-ularge_integer-r1) to simplify 64-bit arithmetic in the Windows version.

One question for you: Have you tried building and running this from a Mac? After reading [this](https://stackoverflow.com/questions/7063303/macro-unix-not-defined-in-macos-x), I suspect this code will not use `gettimeofday` as intended, and will fall back to the 1-second warning. So we may need to tweak the conditional compilation in that case.

**Comment by KJ7LNW** [comment]
> Have you tried building and running [this](https://stackoverflow.com/questions/7063303/macro-unix-not-defined-in-macos-x) from a Mac? After reading this, I suspect this code will not use gettimeofday as intended, and will fall back to the 1-second warning.

Good catch, I had not. I just force-pushed the change.

Thanks for taking care of whitespace/style on your side.  Let me know how it goes in testing!

**Comment by cosinekitty** [comment]
Thank you so much for your contribution! It's really nice to have the more accurate timekeeping now. I made a few more changes on top of what you did:

* In Windows, GetSystemTimeAsFileTime only has millisecond resolution when I test it. I found that GetSystemTimePreciseAsFileTime, a newer function, provides microsecond resolution.
* Minor code simplification and optimization.
* Added unit test to verify it's working on Linux, Mac, and Windows.
* Instead of warning, the code will now produce an error if microsecond resolution is not supported. My rationale is that people ignore warnings and this causes software quality problems. I would rather break the build and force the developer to make a choice.
    * You can completely turn off `Astronomy_CurrentTime`, if your application doesn't need it, by using the compiler option `-D ASTRONOMY_ENGINE_NO_CURRENT_TIME`.
    * You can explicitly opt in to whole second resolution using `-D ASTRONOMY_ENGINE_WHOLE_SECOND`.
* Added user documentation and code comments.

I hope you can review the changes and confirm with your own testing that things look good on your end.

**Comment by KJ7LNW** [comment]
I noticed that Newlib doesn't set `__unix__` so I hacked `__unix__` into our build. 

When you have a moment, please add `__NEWLIB__` in the "UNIX" `#ifdef` section.  You might include these, too:
- `__MUSL__`
- `__UCLIBC__`

and a few others if you want to go crazy with it:
- https://sourceforge.net/p/predef/wiki/Libraries/

**Comment by KJ7LNW** [comment]
It occurs to me that Newlib and uClibc are for embedded systems, so the developer needs to implement their own low-level time-keeping.  Thus, they do provide time out of the box, but they do have all the function stubs and structs to support `gettimeofday`.  I'll leave it to your design decision on how Astronomy Engine should handle this situation.

**Comment by cosinekitty** [comment]
My best guess at this point is to leave it as-is. The [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it) principle suggests that it's better to wait until someone with a specific unsatisfied use case shows up, then figure out how to help that person.

Thanks again for your contribution!

**Pull request merged**
