### PR TITLE
Python: Few typehints for initial review

### PR DESCRIPTION
**Pull request by ris-tlp**
Hi! I've written a few type hints for the first couple of classes/methods in reference to #276. I'd like to see if you're fine with them and I'll proceed then.

image

Comments:
- The reason there are some type hints written within quotations is because they're referencing a class that's defined before they are being referenced, which allows delayed annotations.

Issues: 
- I'm not exactly sure what's happening within the `__init__.py` file but it causes an issue with Mypy where it says the astronomy module doesn't exist. Any clarification on the init file would be great!
- I tried `from typing import Union` to allow a variable to have 2 different types. For example, the constructor of the `Time` class has a small segment where it checks if the`tt` variable is a string and does something else (lines 732-735). I ran into issues with `pydown.py`:
```
Generating Python documentation.
FATAL(pydown): Undocumented symbol: Union
ERROR(./makedoc): Error generating Markdown from Python source.
```
Am I supposed to declare a new import somewhere in the documentation?

Thanks!

### CODE REVIEW

**Comment by cosinekitty** [comment]
This looks like a great start. I'm stoked!

About the `__init__.py`, I'm not sure what to do. The thing is, I don't know nearly as much as I want about creating Python packages. I basically Googled stuff and groped around blindly until I got something that worked to upload the package [astronomy-engine](https://pypi.org/project/astronomy-engine/) on PyPI. If you look at the contents of the package init file, you will see it is very simple. Astronomy Engine itself has a simple structure: one source file and no external third-party dependencies. So please feel free to tinker with that file to get things working.

Regarding the issues with pydown, I'm not surprised. Pydown is my own creation, because I needed something that generated GitHub flavored Markdown documentation. It was faster and easier to write my own generator than to fight with existing tools that are overly opinionated about how things should be formatted. That said, pydown is very primitive and brittle. So I will fix this issue in Pydown.

Which brings me to the next item. I think it will work better for both of us to develop iteratively if I create a topic branch, merge the above changes into it, then fix pydown. I also need to merge in a change I made over the weekend: I added a new function `HourAngle`. Then you could proceed from that point to make more progress.

The idea is, instead of working directly in the `master` branch, I will create a new branch called `python_type_hints`, and that will be the target for your pull requests going forward. That way we can experiment and freely make messes without affecting the live code and documentation that people use for reference.

That means I need to leave this PR here until I get your existing work integrated into the new branch. I believe after that, you would create a new PR referencing the new branch `python_type_hints`.

Does this sound like a good plan to you? Please let me know if there is a better way to do this...

**Comment by cosinekitty** [comment]
Oh, I just tried using mypy's `-m` option, and it might help resolve the issue with `__init__.py`:

```
don@spearmint:~/github/astronomy/source/python/astronomy $ mypy -m astronomy
Success: no issues found in 1 source file
```

Apparently you have to tell mypy that you are analyzing a module file, not a normal Python program?

**Comment by cosinekitty** [comment]
Update: I went ahead and created the new branch [python_type_hints](https://github.com/cosinekitty/astronomy/tree/python_type_hints) that includes your work so far. I added 3 more commits to it:

* 740ef86d31c488daa284bcfd1da24eacddf0313d runs mypy as part of the build process, both on the contributor's local system and in GitHub Actions.
* d73d271a4fdd163a564772ff5fa31198c2a6ab08 includes the use of Union to fix the typing problem in the Time constructor, and fixes the resulting problems in pydown.
* f87b600955fb1fa1e39a256abb43ccb9558cd152 documents that contributors need to install pylint and mypy.

I still want to support Python 3.7, so I was not able to use the vertical bar syntax `float | str` for the type signature in the Time constructor. That syntax requires 3.10+. That's why I had to express it this way:

```python
    def __init__(self, ut : Union[float, str], tt = None):
```

I believe you can now resume work from the current state of python_type_hints. I'm not sure the best way to do that with GitHub. If you need to delete your current fork and re-create it, it will delete this PR and discussion with it, but at least your work and your status as a contributor are already part of my python_type_hints branch. Or maybe you can find a way to update your fork and switch to the new branch to submit another PR from it?

**Comment by ris-tlp** [comment]
Totally agree with you on working in a new branch, definitely the right way to go. I was able to sync the new branch to my fork and create a new PR (#289) so I'll be making changes on that PR now. I'll close this PR so the discussion can remain here.

Thanks for the fixes regarding Pydown and adding mypy to the build process, really convenient! And I didn't know about running mypy throughout an entire module, great find! Definitely solves the issue I was having earlier.  All this should iron out any quirks and hopefully should be smooth sailing from now on, thanks!

**Pull request closed without merging**
