### PR TITLE
Add dart project structure

### PR DESCRIPTION
**Pull request by HrBDev**

### CODE REVIEW

**Comment by cosinekitty** [comment]
Hello @HrBDev and welcome to the project! You must be the person @ebraminio mentioned as a Dart developer who could help? This looks like a great start!

I would like to keep this pull request open while we are finishing up the Kotlin release. Once that has been merged into the `master` branch, I will create a new `dart` branch and merge this into it. Thank you so much for helping us get started! It might take a couple more weeks before I'm ready to do that, so please know that I will come back to this as soon as the time is right.

**Comment by ebraminio** [comment]
> You must be the person @ebraminio mentioned as a Dart developer who could help? This looks like a great start!

Actually I talked with him but wanted to do that myself but he was interested about it the far that went ahead and initially I wasn't aware about it 😁

> Once that has been merged into the master branch, I will create a new dart branch and merge this into it.

Make sense and I was expecting that, I can send PR to his branch to specially implement Time object that is a bit better than Kotlin.

**Comment by ebraminio** [comment]
Thank you for the public release @cosinekitty :) So now we now we can get rid of Kotlin branch which apparently is not deleted and have a Dart branch instead and afterwards @HrBDev can rebase and retarget this PR to that branch in order to get started.

As a general note Kotlin's naming convention is better to be followed in Dart one rather other implementation as they have similar naming convention. JavaScript also uses a similar to Java which Kotlin also follow naming convention but not breaking users code is an important thing so let's just focus on Dart one instead.

Btw I just updated my app with the public release of the library https://github.com/persian-calendar/persian-calendar/commit/ac8d2f0428657a0e2df80e50045923a5b1d5abd5 and have done this yesterday hope you like :)

https://user-images.githubusercontent.com/833473/167079683-fdc01c3e-3c5e-4b14-b6ee-061af13b5e30.mov

**Comment by cosinekitty** [comment]
I am glad the JitPack publish worked. I still don't understand the details of deployment as much as I would like, but it's great that you could verify it.

I just deleted the `kotlin` branch. I waited to make sure all tests passed and it looks stable in `master`. 

Also, I will create a `dart` branch soon and bring in this pull request from @HrBDev. It may be a week or two before I begin much work on Dart, because there are a few other things I want to do first. But we will do it!

**Comment by cosinekitty** [comment]
I have created the new branch `dart` and merged this pull request into it. As mentioned above, it may be a week or two before I do much more. But it is great to get started. Thanks @HrBDev for getting involved in this project!

**Comment by cosinekitty** [comment]
This has already been merged into the new branch called `dart`.

**Pull request closed without merging**
