### PR TITLE
Add Kotlin project structure

### PR DESCRIPTION
**Pull request by ebraminio**
As https://github.com/cosinekitty/astronomy/discussions/109#discussioncomment-2366537

```
cd source/kotlin
./gradlew test # runs the test suite
./gradlew dokkaHtml # generates documentation
```

### CODE REVIEW

**Comment by ebraminio** [comment]
CI failures seem unrelated as far as I can tell.

**Comment by ebraminio** [comment]
It passes here https://github.com/ebraminio/astronomy/runs/5558334601?check_suite_focus=true

**Comment by cosinekitty** [comment]
I was looking at those also. All of those failures are Netlify complaining about a nonexistent directory `/opt/build/repo/website`, but I can't figure out where that is coming from.

**Comment by ebraminio** [comment]
CI passes on my fork https://github.com/ebraminio/astronomy apparently

**Comment by ebraminio** [comment]
Thanks! Feel free to ask any thing here, somehow GitHub's Issues UI works better than discussion one.

As said before there an essential binary file between the project structure at `source/kotlin/gradle/wrapper/gradle-wrapper.jar`, I specifically added `- uses: gradle/wrapper-validation-action@v1` to check its validity but feel free to check it manually also if it matches gradle one before opening the project in IDE, https://docs.gradle.org/current/userguide/gradle_wrapper.html#wrapper_checksum_verification

Thanks :)

**Comment by cosinekitty** [comment]
A few more things:
1. We need this stuff to work in the Mac OS and Windows environments also, so that needs to be added to `.github/workflows/astronomy-engine-tests.yml`.
2. One thing that is not obvious: there is a script `generate/makedoc` (or `generate/makedoc.bat` in Windows) that runs a code generator. The makedoc is executed by the `generate/run` script from the GitHub Actions yml file. This step is needed to inject various tables of numbers into the source code. The code generator must run before building any code, including the new Kotlin code, because it will modify the Kotlin code. It looks like this one is OK, because the Kotlin build happens after. However, I may want to rework the Kotlin build and unit tests to be invoked by the `run` command, so I can make them happen at exactly the right time. (See the next item for the reason.)
3. Some of the unit testing will include running code written in C, not Kotlin, because I have a C program that compares calculations written to files, to make sure the different languages are calculating the same numbers. Hopefully it is not hard to add an extra step for this?

I know this may be confusing, but perhaps take a look at the following parts of `generate/run` script, where it calls other scripts:

```bash
./unit_test_csharp $1 || exit $?
./unit_test_js $1 || exit $?
./unit_test_c $1 || exit $?
./unit_test_python $1 || exit $?

./diffcalc || exit $?
```

It would be ideal to add yet another script `unit_test_kotlin` here, before the call to `diffcalc`. That way, if `diffcalc` fails, I know there is a discrepancy that the per-language unit tests failed to notice.

**Comment by cosinekitty** [comment]
Actually, @ebraminio, I think you have done enough to get me started... so I will work on the items I mentioned. Thank you very much!  Also, the Netlify part is working now, so perhaps they had a temporary outage?

**Comment by ebraminio** [comment]
> We need this stuff to work in the Mac OS and Windows environments also, so that needs to be added to .github/workflows/astronomy-engine-tests.yml.

Let's see https://github.com/cosinekitty/astronomy/pull/168

Regard 2 and 3, so you some command to be executed somewhere along the build? That is of course possible but risky I should.

And more idiomatic way to do codegen in Kotlin is KotllinPoet but I think that is too much to start with

> the Netlify part is working now, so perhaps they had a temporary outage?

I think it might be because of configs and difference they put between PR and a commit in repository, just a naïve guess.

**Comment by cosinekitty** [comment]
Thanks again! I have merged the pull request. About items 2 and 3, I think it will be fine. I just need to move some of the commands you have in the yml file into my scripts, where I can execute them at the right time.

I already have a strange situation in the existing 4 languages, where I maintain "templates" of the code in the `generate/template` directory. They have placeholders where generated arrays of numbers need to be inserted. The code generator reads these files and writes the output into the `source` directory with the placeholders expanded. It's basically a custom macro system. The unit tests must be compiled (C and C#) and run (all 4 languages) after the code generator runs, or they are not guaranteed to be running the latest version of the astronomy code.

When I push a new change to GitHub, I have already run the code generator and committed both the templates and output source to git. Part of the CI process is to run the code generator *again* and verify that git doesn't see any local changes (i.e. the code generator produces exactly the same source code that is checked into git). If there are any differences detected by git, I fail the build because it means either the published code is stale or something is wrong with the code generator.

I will need to do the same thing for Kotlin as I do for the other 4 languages, which is why I need more control over the sequence of steps. Like I said, I believe I can handle this part, but if I run into confusion I will definitely ask for your help again.

**Pull request merged**
